CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL, updated_at timestamp(6) NOT NULL,
    auth_provider varchar(20) NOT NULL, deleted_at timestamp(6), email varchar(255) NOT NULL,
    nickname varchar(50) NOT NULL, password varchar(255), provider_id varchar(255),
    role varchar(20) NOT NULL, status varchar(20) NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT users_auth_provider_check CHECK (auth_provider IN ('LOCAL','GOOGLE','GITHUB')),
    CONSTRAINT users_role_check CHECK (role IN ('USER','ADMIN')),
    CONSTRAINT users_status_check CHECK (status IN ('ACTIVE','DELETED'))
);

CREATE TABLE companies (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL, updated_at timestamp(6) NOT NULL,
    logo_url varchar(255), name varchar(100) NOT NULL, normalized_name varchar(100) NOT NULL,
    website_url varchar(255), CONSTRAINT uk_companies_normalized_name UNIQUE (normalized_name)
);

CREATE TABLE job_positions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL, updated_at timestamp(6) NOT NULL,
    interview_criteria text, name varchar(100) NOT NULL, normalized_name varchar(100) NOT NULL,
    tech_stack jsonb, company_id bigint NOT NULL REFERENCES companies(id),
    CONSTRAINT uk_job_positions_company_normalized_name UNIQUE (company_id, normalized_name)
);

CREATE TABLE job_postings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL, updated_at timestamp(6) NOT NULL,
    extracted_content text NOT NULL, posting_url text NOT NULL, title varchar(255),
    job_position_id bigint NOT NULL REFERENCES job_positions(id), user_id bigint REFERENCES users(id)
);

CREATE TABLE job_posting_analyses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL, updated_at timestamp(6) NOT NULL,
    ai_model varchar(100) NOT NULL, analyzed_at timestamp(6) NOT NULL,
    company_name varchar(100), experience_requirements jsonb NOT NULL, keywords jsonb NOT NULL,
    position_name varchar(100), preferred_qualifications jsonb NOT NULL,
    required_qualifications jsonb NOT NULL, responsibilities jsonb NOT NULL,
    summary text, tech_stack jsonb NOT NULL,
    job_posting_id bigint NOT NULL UNIQUE REFERENCES job_postings(id)
);

CREATE TABLE resumes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL, updated_at timestamp(6) NOT NULL,
    content_type varchar(100) NOT NULL, extracted_text text NOT NULL, file_hash varchar(64) NOT NULL,
    file_size bigint NOT NULL, original_file_name varchar(255) NOT NULL,
    user_id bigint NOT NULL REFERENCES users(id)
);

CREATE TABLE resume_analyses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL, updated_at timestamp(6) NOT NULL,
    achievements jsonb NOT NULL, ai_model varchar(100) NOT NULL, analyzed_at timestamp(6) NOT NULL,
    certifications jsonb NOT NULL, education jsonb NOT NULL, keywords jsonb NOT NULL,
    projects jsonb NOT NULL, skills jsonb NOT NULL, strengths jsonb NOT NULL, summary text,
    work_experiences jsonb NOT NULL, resume_id bigint NOT NULL UNIQUE REFERENCES resumes(id)
);

CREATE TABLE interviews (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL, updated_at timestamp(6) NOT NULL,
    cancelled_at timestamp(6), completed_at timestamp(6), started_at timestamp(6),
    status varchar(20) NOT NULL, title varchar(100) NOT NULL,
    job_position_id bigint REFERENCES job_positions(id), job_posting_id bigint REFERENCES job_postings(id),
    resume_id bigint REFERENCES resumes(id), user_id bigint NOT NULL REFERENCES users(id),
    CONSTRAINT interviews_status_check CHECK (status IN ('READY','IN_PROGRESS','COMPLETED','CANCELLED'))
);

CREATE TABLE interview_questions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL, updated_at timestamp(6) NOT NULL,
    category varchar(20), content text NOT NULL, difficulty varchar(20), is_ai_generated boolean NOT NULL,
    question_order integer NOT NULL, type varchar(20), interview_id bigint NOT NULL REFERENCES interviews(id),
    parent_question_id bigint UNIQUE REFERENCES interview_questions(id),
    CONSTRAINT uk_interview_question_order UNIQUE (interview_id, question_order),
    CONSTRAINT interview_questions_category_check CHECK (category IN ('CS','TECH_STACK','EXPERIENCE','SITUATION','COMPANY_FIT')),
    CONSTRAINT interview_questions_difficulty_check CHECK (difficulty IN ('EASY','MEDIUM','HARD')),
    CONSTRAINT interview_questions_type_check CHECK (type IN ('NORMAL','FOLLOW_UP'))
);

CREATE TABLE interview_answers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL, updated_at timestamp(6) NOT NULL,
    answer_content text NOT NULL, answered_at timestamp(6) NOT NULL,
    question_id bigint NOT NULL UNIQUE REFERENCES interview_questions(id)
);

CREATE TABLE question_evaluations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL, updated_at timestamp(6) NOT NULL,
    ai_model varchar(50) NOT NULL, improvement_suggestion text NOT NULL, reasoning text NOT NULL,
    score integer NOT NULL, strengths text NOT NULL, weaknesses text NOT NULL,
    answer_id bigint NOT NULL UNIQUE REFERENCES interview_answers(id)
);

CREATE TABLE feedbacks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL, updated_at timestamp(6) NOT NULL,
    ai_model varchar(50) NOT NULL, answered_count integer NOT NULL,
    improvement_suggestions text NOT NULL, overall_score integer, partial boolean NOT NULL,
    strengths text NOT NULL, summary text NOT NULL, total_question_count integer NOT NULL,
    weaknesses text NOT NULL, interview_id bigint NOT NULL UNIQUE REFERENCES interviews(id)
);
