spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/ai_interview
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true
server:
    port: 8081

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: ${SPRINGDOC_ENABLED:true}
  swagger-ui:
    path: /swagger-ui.html
    enabled: ${SPRINGDOC_ENABLED:true}
    operations-sorter: alpha
  default-consumes-media-type: application/json
  default-produces-media-type: application/json